M48
; DRILL file {KiCad 7.0.5} date Thu Nov  9 00:00:07 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-09T00:00:07-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1268
%
G90
G05
T1
X1.9Y-2.5
X1.9Y-3.25
X4.3Y-2.5
X4.3Y-3.25
T2
X2.3Y-2.65
X2.3Y-3.1201
T0
M30
